### ISSUE TITLE
Feedback from developers

### ISSUE THREAD

**Issue by harrythecode** [amezousan/adalo-twitter-timeline#5]
I've got the review below:
--
- [x] Change "Screen name" to "Twitter Handle"
- [x] Move the information in the parentheses next to "Screen Name" to help text, and say "Don't include the @ sign" before you give the example. See https://developers.adalo.com/api-reference/configuration/manifest-json#helptext
- [x] Currently, the bounding box in the editor has no bearing on the actual height of the component. It would be a lot better if the height of the component was tied to the height of the bounding box instead of a prop. So please remove the "Timeline Height" from the manifest and use the height instead. Every component is passed a _height prop through react that you can probably use to achieve this.
- [x] Currently, there's no check to make sure the twitter handle is valid. Because of this, the component immediately crashes when you try to change the twitter handle in the editor. Plus, the text input should be able to handle magic text, which won't resolve to an actual string until the previewer. I would recommend checking for the validity of the twitter handle, and if it's invalid, displaying some sort of placeholder image.
- [x] For the number of tweets to show, instead of mapping unlimited to '0', add a switch above the tweet count that says "Limit the number of tweets?", and if it's set to true, then display the tweet count prop. You can find information on how to do this at: https://developers.adalo.com/docs/interactions/conditional-control
- [x] For the language prop, I think it'll be more intuitive if you move the content inside the parentheses into the help text, and included a link to the ISO standard for reference.
- [x] The two child components you have are small enough and similar enough that I think you could combine them into the same child component

**Comment by harrythecode** [comment]
> Currently, the bounding box in the editor has no bearing on the actual height of the component. It would be a lot better if the height of the component was tied to the height of the bounding box instead of a prop. So please remove the "Timeline Height" from the manifest and use the height instead. Every component is passed a _height prop through react that you can probably use to achieve this.

I changed it to use the `_height` prop by default. However, timeline should be able to have a "null" value when it will be stretched out to the bottom. I have no idea how I can control the height prop in both editor and preview, so I just let the "Timeline Height" be optional so that users can choose either.

> Currently, there's no check to make sure the twitter handle is valid. Because of this, the component immediately crashes when you try to change the twitter handle in the editor. Plus, the text input should be able to handle magic text, which won't resolve to an actual string until the previewer. I would recommend checking for the validity of the twitter handle, and if it's invalid, displaying some sort of placeholder image.

I disabled the preview of timeline on editor not to be crashed immediately. I'm just wondering how I can implement these:
- the text input should be able to handle magic text
- checking for the validity of the twitter handle ( A proper way is to create a new API to lookup Twitter users but it will hit a rate limit of Twitter APIs quickly when I allow users to use the API. Of course, I can subscribe Premium plan but it costs much... Here is one available Twitter API for looking up users: https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup)

**Comment by scott-massey** [comment]
For your height issue, what you could do is have a "Restrict Timeline Height" boolean prop. When it's set to true, you can conditionally show the timeline height prop. 

The idea is that if an error gets thrown in the editor for an unknown username, display a placeholder image instead of throwing the error. Currently, when you try to change the twitter handle in the editor, it automatically tries to reload the component and immediately crashes.

**Comment by harrythecode** [comment]
> For your height issue, what you could do is have a "Restrict Timeline Height" boolean prop. When it's set to true, you can conditionally show the timeline height prop.

Sounds a good idea :) I'll fix it.

> The idea is that if an error gets thrown in the editor for an unknown username, display a placeholder image instead of throwing the error. Currently, when you try to change the twitter handle in the editor, it automatically tries to reload the component and immediately crashes.

I've already implemented the placeholder feature at https://github.com/amezousan/adalo-twitter-timeline/blob/d27787e80f41e4ced0454a0f89eb4c43a8915e7a/src/components/TwitterTimeline/index.js#L102

My concern is whether I need to implement a proper error message for all devices(iOS/Android). The placeholder will work only in Web (not in iOS/Android) since React will throw an error but the WebView does not. In the beginning, I think the current error handling is enough but of course, it'd be better to have the same error message views in all devices (Web/iOS/Android).

<img width="889" alt="Screenshot 2020-09-14 at 17 28 52" src="https://user-images.githubusercontent.com/4526936/93106273-5ccf7c00-f6b0-11ea-8d02-944b3a9241a5.png">

**Comment by scott-massey** [comment]
You might be able to use [this](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#communicating-between-js-and-native) to add an event listener for the error, if one exists. I don't think it's a major issue if they're different, but yes ideally you would see the same error on all platforms.

It would be great if you could look into it to see if you can make it work with the webview, but if it's truly impossible or looks like it would take a long time it's not worth it.

**Comment by harrythecode** [comment]
@scott-massey Thank you for the feedback! I've managed somehow to catch an error in WebView and implement the placeholder. I'll merge the changes with a new pull request and publish it to your side :)

<img width="400" alt="Screenshot 2020-09-15 at 09 11 36" src="https://user-images.githubusercontent.com/4526936/93180371-559f8100-f737-11ea-8086-bc654b877196.png">

**Comment by harrythecode** [comment]
This is done.
